name: CI

on:
  push:
    branches:
      - 'dev'
      - 'main'
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init node/yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Build
        run: |
          yarn install
          yarn prep:rinkeby
          yarn test
          yarn build
