name: Deploy devnet

on:
  push:
    branches:
      - 'testnet'

jobs:
  deploy-testnet:
    name: Deploy testnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init node/yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Build and deploy testnet
        run: |
          yarn install
          yarn prep:testnet
          yarn build
          yarn auth ${{ secrets.GRAPH_DEPLOY_KEY }}
          yarn deploy:testnet
