name: Deploy mainnet

on:
  push:
    branches:
      - 'mainnet'

jobs:
  deploy-mainnet:
    name: Deploy mainnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init node/yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Build and deploy mainnet
        run: |
          yarn install
          yarn prep:mainnet
          yarn build
          yarn auth ${{ secrets.GRAPH_DEPLOY_KEY }}
          yarn deploy:mainnet
