name: Deploy devnet

on:
  push:
    branches:
      - 'dev'

jobs:
  deploy-devnet:
    name: Deploy devnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init node/yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Build and deploy devnet
        run: |
          yarn install
          yarn prep:devnet
          yarn build
          yarn auth ${{ secrets.GRAPH_DEPLOY_KEY }}
          yarn deploy:devnet
